const json=require('json-server')
const server=json.create()
const cors=require('cors')
const router=json.router('./db.json')
const middleware=json.defaults()
const port=process.env.PORT || 3001
server.use(middleware)
server.use(cors())
server.use(router)
server.listen(port)